[metadata]
name = erpnext
version = attr: erpnext.__version__
description = Open Source alternative to SAP
url = https://erpnext.com
author = Frappe Technologies
author_email = info@frappe.io
maintainer = Frappe Technologies
maintainer_email = developers@frappe.io
keywords = ERP
license = GPLv3
classifiers =
    Development Status :: 5 - Production/Stable
    Intended Audience :: Developers
    License :: OSI Approved :: GPLv3 License
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: Implementation :: CPython
    Topic :: Office/Business
    Topic :: Office/Business :: Financial :: Accounting
    Topic :: Office/Business :: Financial :: Point-Of-Sale
project_urls =
    Documentation = https://docs.erpnext.com
    Release Notes = https://github.com/frappe/erpnext/releases
    Source = https://github.com/frappe/erpnext

[options]
python_requires = >=3.6
packages = find:
include_package_data = true
zip_safe = false
install_requires =
    gocardless-pro~=1.22.0
    googlemaps  # used in ERPNext, but dependency is defined in Frappe
    pandas~=1.1.5
    plaid-python~=7.2.1
    pycountry~=20.7.3
    PyGithub~=1.54.1
    python-stdnum~=1.16
    python-youtube~=0.8.0
    taxjar~=1.9.2
    tweepy~=3.10.0
    Unidecode~=1.2.0
    WooCommerce~=3.0.0
